version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: "/forum.yourcontrols.xyz/client"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - safeshows
    assignees:
      - safeshows
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: "/forum.yourcontrols.xyz/client"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - safeshows
    assignees:
      - safeshows
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
